### ISSUE TITLE
Problem with constexpr

### ISSUE THREAD

**Issue by carmeloevoli** [adundovi/hermes#2]
error in ``/hermes/include/hermes/units/UnitsBasic.h:298:18``

``
constexpr double sqrt(double num) {
    return std::sqrt(num);
}
``

constexpr function never produces a constant expression [-Winvalid-constexpr]
note: non-constexpr function 'sqrt' cannot be used in a constant expression

it could be a Mac compilar issue.

**Comment by adundovi** [comment]
Do you use GCC or clang? Clang doesn't support this for a moment, and I should change it :-/

**Comment by carmeloevoli** [comment]
yes I'm using Clang, how can I say cmake which compiler to be used?

**Comment by adundovi** [comment]
Put full paths to C, C++ and Fortran GCC compilers in env variables CC, CXX, and FC, respectively.
``sh
export CXX=/usr/bin/g++
```
